export const COPY = {
  title: "People",
  add: "Add",
  addPerson: "Add person",
  searchLabel: "Search",
  countryLabel: "Country",
  departmentLabel: "Department",
  levelLabel: "Level",
  statusLabel: "Status",
  any: "Any",
  statusActive: "Active",
  statusLeft: "Left",
  loading: "Loading people",
  loadError: "Could not load people.",
  retry: "Retry",
  empty: "No people match these filters.",
  pageLabel: "Page",
  totalLabel: "Total",
  previous: "Previous",
  next: "Next",
  figuresTitle: "Pay figures",
  headcount: "Headcount",
  median: "Median",
  totalPay: "Total",
  noDepartment: "No department",
  columnEmployee: "Employee",
  columnCountry: "Country",
  columnLevel: "Level",
  columnDepartment: "Department",
  columnBase: "Annual base",
  columnStatus: "Status",
  save: "Save",
  saving: "Saving",
  employeeIdLabel: "Employee id",
  legalNameLabel: "Legal name",
  currencyLabel: "Currency",
  annualBaseLabel: "Annual base",
  monthlyLabel: "Monthly",
  managerLabel: "Manager id",
  startDateLabel: "Start date",
  leaveDateLabel: "Leave date",
  noteLabel: "Note",
  noteHint: "Required for this change.",
  changesTitle: "Changes",
  noChanges: "No changes yet.",
  duplicateId: "The employee id is already on file.",
  leaveDateRequired: "Leave date is required when status is left.",
  noteRequired: "A note is required.",
  saveError: "Could not save this person.",
  personLoading: "Loading person",
  personLoadError: "Could not load this person.",
  bandsNav: "Bands",
  bandsTitle: "Bands",
  changesLoading: "Loading changes",
  changesLoadError: "Could not load changes.",
  changesEmpty: "No pay, country, or employment changes in the last 30 days.",
  columnPerson: "Person",
  columnOldBase: "Old base",
  columnNewBase: "New base",
  columnOldCountry: "Old country",
  columnDate: "Date",
  columnNote: "Note",
  bandsLoading: "Loading bands",
  bandsLoadError: "Could not load bands.",
  noBand: "no band",
  setBand: "Set",
  clearBand: "Clear",
  minBaseLabel: "Minimum",
  maxBaseLabel: "Maximum",
  openOutside: "Outside",
  outsideLoading: "Loading people outside this band",
  outsideLoadError: "Could not load people outside this band.",
  outsideEmpty: "Nobody is outside this band.",
  columnMin: "Minimum",
  columnMax: "Maximum",
  columnGap: "Gap",
  columnSide: "Side",
  sideUnder: "under",
  sideOver: "over",
  bandSaveError: "Could not save this band.",
  bandClearError: "Could not clear this band.",
} as const;
