export const COPY = {
  title: "People",
  add: "Add",
  addPerson: "Add person",
  searchLabel: "Search",
  countryLabel: "Country",
  departmentLabel: "Department",
  levelLabel: "Level",
  statusLabel: "Status",
  any: "Any",
  statusActive: "Active",
  statusLeft: "Left",
  loading: "Loading people",
  loadError: "Could not load people.",
  retry: "Retry",
  empty: "No people match these filters.",
  pageLabel: "Page",
  totalLabel: "Total",
  previous: "Previous",
  next: "Next",
  figuresTitle: "Pay figures",
  headcount: "Headcount",
  median: "Median",
  totalPay: "Total",
  noDepartment: "No department",
  columnEmployee: "Employee",
  columnCountry: "Country",
  columnLevel: "Level",
  columnDepartment: "Department",
  columnBase: "Annual base",
  columnStatus: "Status",
} as const;
