import type { QueryInterface } from "sequelize";

const countryCurrency = `
  (country = 'India' AND currency = 'INR')
  OR (country = 'United States' AND currency = 'USD')
  OR (country = 'United Kingdom' AND currency = 'GBP')
  OR (country = 'Germany' AND currency = 'EUR')
  OR (country = 'Singapore' AND currency = 'SGD')
`;

async function up(queryInterface: QueryInterface): Promise<void> {
  await queryInterface.sequelize.query(`
    CREATE TABLE employees (
      employee_id varchar(64) PRIMARY KEY,
      legal_name varchar(200) NOT NULL,
      country text NOT NULL,
      currency char(3) NOT NULL,
      level text NOT NULL,
      annual_base DECIMAL(12,2) NOT NULL,
      status text NOT NULL,
      leave_date date NULL,
      department text NULL,
      manager_employee_id varchar(64) NULL,
      start_date date NULL,
      CONSTRAINT employees_annual_base_nonnegative CHECK (annual_base >= 0),
      CONSTRAINT employees_country_currency CHECK (${countryCurrency}),
      CONSTRAINT employees_status_leave_date CHECK (
        (status = 'left' AND leave_date IS NOT NULL)
        OR (status = 'active' AND leave_date IS NULL)
      )
    )
  `);

  await queryInterface.sequelize.query(`
    CREATE TABLE salary_changes (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      employee_id varchar(64) NOT NULL REFERENCES employees (employee_id) ON DELETE RESTRICT,
      changed_at timestamptz NOT NULL DEFAULT now(),
      old_base DECIMAL(12,2) NOT NULL,
      new_base DECIMAL(12,2) NOT NULL,
      old_country text NULL,
      new_country text NOT NULL,
      old_status text NOT NULL,
      new_status text NOT NULL,
      note varchar(1000) NOT NULL,
      CONSTRAINT salary_changes_real_change CHECK (
        old_base <> new_base
        OR old_country IS NOT NULL
        OR old_status <> new_status
      ),
      CONSTRAINT salary_changes_old_country CHECK (
        old_country IS NULL OR old_country <> new_country
      )
    )
  `);

  await queryInterface.sequelize.query(`
    CREATE INDEX salary_changes_employee_id_changed_at_idx
      ON salary_changes (employee_id, changed_at DESC)
  `);
  await queryInterface.sequelize.query(`
    CREATE INDEX salary_changes_changed_at_idx
      ON salary_changes (changed_at DESC)
  `);

  await queryInterface.sequelize.query(`
    CREATE TABLE salary_bands (
      country text NOT NULL,
      level text NOT NULL,
      currency char(3) NOT NULL,
      min_base DECIMAL(12,2) NOT NULL,
      max_base DECIMAL(12,2) NOT NULL,
      PRIMARY KEY (country, level),
      CONSTRAINT salary_bands_country_currency CHECK (${countryCurrency}),
      CONSTRAINT salary_bands_bounds CHECK (
        min_base >= 0 AND max_base >= 0 AND min_base <= max_base
      )
    )
  `);
}

async function down(queryInterface: QueryInterface): Promise<void> {
  await queryInterface.sequelize.query("DROP TABLE IF EXISTS salary_changes");
  await queryInterface.sequelize.query("DROP TABLE IF EXISTS salary_bands");
  await queryInterface.sequelize.query("DROP TABLE IF EXISTS employees");
}

export = { up, down };
